In [1]:
import numpy as np
from sklearn import preprocessing 

data = np.array([[3,5],[7,4],[2,4]])
# print(data)

#mean average

mean_value= data.mean(axis=0)
# print(mean_value)

#Standard Deviation

std = data.std(axis=0)
# print(std)

# Mean Removal

final_val = data - mean_value
print(final_val)
# print(final_val.mean(axis=0))
# print(final_val.std(axis=0))

# Scale
final = preprocessing.scale(data)
print(final)
print(final.mean(axis=0))
print(final_val.mean(axis=0))


[[-1.          0.66666667]
 [ 3.         -0.33333333]
 [-2.         -0.33333333]]
[[-0.46291005  1.41421356]
 [ 1.38873015 -0.70710678]
 [-0.9258201  -0.70710678]]
[0.00000000e+00 5.92118946e-16]
[0.00000000e+00 2.96059473e-16]


In [13]:
import pandas as pd

df = pd.read_csv("new.csv")
print(df)
print("\n")
data = df[['Person ','Male','Female']]
print(data)
print("\n")

print(data.mean(axis=0))
print(data.std(axis=0))
print("\n")


mean_remove = preprocessing.scale(data)
print(mean_remove.mean(axis=0))
print(mean_remove.std(axis=0))

print("\n")


# Scalling data in CSV file
data = df[['Person ','Male','Female']]
scaller_model = preprocessing.MinMaxScaler()
op = scaller_model.fit_transform(data)
print(op)

   Year   Person    Male  Female
0   1951    18.33  27.15    8.58
1   1961    25.65  40.26   15.35
2   1971    26.95  45.96   21.97
3   1981    28.56  56.38   29.73
4   1991    30.24  64.13   39.23
5   2001    33.52  75.14   53.25


   Person    Male  Female
0    18.33  27.15    8.58
1    25.65  40.26   15.35
2    26.95  45.96   21.97
3    28.56  56.38   29.73
4    30.24  64.13   39.23
5    33.52  75.14   53.25


Person     27.208333
Male       51.503333
Female     28.018333
dtype: float64
Person      5.141499
Male       17.275026
Female     16.371842
dtype: float64


[1.11022302e-16 1.85037171e-16 1.11022302e-16]
[1. 1. 1.]


[[0.         0.         0.        ]
 [0.48189598 0.27318191 0.15155585]
 [0.5674786  0.39195666 0.29975375]
 [0.67346939 0.60908523 0.47347213]
 [0.78406847 0.7705772  0.68614283]
 [1.         1.         1.        ]]


In [11]:
data = np.array([[3,5],[7,4],[2,4]])

# Define a Scaller Model for data scalling
scaller_model = preprocessing.MinMaxScaler()

# Apply Fit Method to data
op1 = scaller_model.fit(data)
# print(op1)


# Apply Transform Method to data
 
op2 = op1.transform(data)
print(op2)


[[0.2 1. ]
 [1.  0. ]
 [0.  0. ]]


In [12]:
data = np.array([[3,5],[7,4],[2,4]])
scaller_model = preprocessing.MinMaxScaler()
op = scaller_model.fit_transform(data)
print(op)

[[0.2 1. ]
 [1.  0. ]
 [0.  0. ]]
